In [1]:
import torch

USE_CUDA = torch.cuda.is_available()
print(USE_CUDA)

device = torch.device('cuda:0' if USE_CUDA else 'cpu')
print('Learning device:',device)

True
Learning device: cuda:0


In [2]:
x = torch.rand(3, 3).to(device) # 'to' command specifies to use GPU. 
x

tensor([[0.6973, 0.0277, 0.9953],
        [0.8016, 0.0460, 0.9496],
        [0.2498, 0.0091, 0.1115]], device='cuda:0')

In [3]:
a = torch.rand(3, 3)
a.unsqueeze(0) # Add 1 dimension to 0. At this point, row will expand [1, 3, 3] view.
# a


tensor([[[0.3901, 0.5957, 0.7981],
         [0.8502, 0.8054, 0.5692],
         [0.3960, 0.5578, 0.9703]]])

In [4]:
a.squeeze(0) # Remove 1 dimension in 0 position.
a

tensor([[0.3901, 0.5957, 0.7981],
        [0.8502, 0.8054, 0.5692],
        [0.3960, 0.5578, 0.9703]])

In [5]:
a = torch.Tensor([1,1,1,0,1])
torch.nonzero(a, as_tuple=True) # Extract indexes of nonzero.

(tensor([0, 1, 2, 4]),)

In [6]:
a = torch.rand(3,1)
a.expand(-1,4) # Expand dimesion from [3,1] to [3,4]. -1 means original value which that positioned.
#a

tensor([[0.8792, 0.8792, 0.8792, 0.8792],
        [0.2848, 0.2848, 0.2848, 0.2848],
        [0.6613, 0.6613, 0.6613, 0.6613]])

In [7]:
a = torch.rand(3, 4, 5)
b = torch.rand(5, 4)
torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size())) # [1, 5, 4]: after unsqueeze, [3, 5, 4]: after expand. 

tensor([[[1.5381, 1.2186, 1.6590, 1.4749],
         [0.7487, 1.0538, 0.8610, 0.6265],
         [2.1759, 1.8604, 2.1462, 1.9033],
         [1.4718, 1.2910, 1.5501, 1.3097]],

        [[1.2881, 0.8331, 1.1940, 0.8739],
         [1.2272, 1.2528, 1.4128, 1.0805],
         [0.3622, 0.9338, 0.7167, 0.3830],
         [0.6900, 0.3340, 0.5654, 0.7627]],

        [[1.2394, 1.2748, 1.2783, 1.1851],
         [1.7546, 0.8579, 1.4234, 1.4415],
         [2.1229, 1.2881, 1.8741, 1.9022],
         [1.8442, 1.4590, 1.8377, 1.6005]]])